#ifndef BK_LCD_INTROSPECTION_H
#define BK_LCD_INTROSPECTION_H

#include QMK_KEYBOARD_H

#ifdef RP_I2C_USE_I2C0
#    undef RP_I2C_USE_I2C0
#endif
#define RP_I2C_USE_I2C0 FALSE

#ifdef RP_I2C_USE_I2C1
#    undef RP_I2C_USE_I2C1
#endif
#define RP_I2C_USE_I2C1 TRUE

#define SPLIT_TRANSACTION_IDS_MODULE_LCD RPC_ID_MOUSE_SYNC

#endif // BK_LCD_INTROSPECTION_H