#include QMK_KEYBOARD_H
#include "theme.h"
#include "ui_elements.h"

ui_styles_t  theme_style;

LV_FONT_DECLARE(montserratbold14);
LV_FONT_DECLARE(montserratbold13);
LV_FONT_DECLARE(dmsans13);
LV_FONT_DECLARE(dmsans14);
LV_FONT_DECLARE(dmsans14bold);
LV_FONT_DECLARE(jetbrainsmono13);
LV_FONT_DECLARE(jetbrainsmono14bold);

void init_themes(void) {
// ─────────────────────────────────────────────────────
// BastardKB · Custom Theme
// Generated by BastardKB Theme Editor
// ─────────────────────────────────────────────────────

// ── mod_btn · normal ─────────────────────────────────
lv_style_init(&(theme_style.mod_btn));
lv_style_set_text_font(&(theme_style.mod_btn), &montserratbold14);
lv_style_set_radius(&(theme_style.mod_btn), 10);
lv_style_set_bg_opa(&(theme_style.mod_btn), LV_OPA_COVER);
lv_style_set_bg_color(&(theme_style.mod_btn), lv_color_make(42, 47, 40));
lv_style_set_bg_grad_color(&(theme_style.mod_btn), lv_color_make(35, 38, 33));
lv_style_set_bg_grad_dir(&(theme_style.mod_btn), LV_GRAD_DIR_VER);
lv_style_set_border_color(&(theme_style.mod_btn), lv_color_make(17, 19, 16));
lv_style_set_border_width(&(theme_style.mod_btn), 3);
lv_style_set_border_side(&(theme_style.mod_btn), LV_BORDER_SIDE_NONE);
lv_style_set_text_color(&(theme_style.mod_btn), lv_color_make(255, 255, 255));
lv_style_set_text_opa(&(theme_style.mod_btn), 184);
lv_style_set_pad_top(&(theme_style.mod_btn), 11);
lv_style_set_pad_bottom(&(theme_style.mod_btn), 11);
lv_style_set_pad_left(&(theme_style.mod_btn), 0);
lv_style_set_pad_right(&(theme_style.mod_btn), 0);
lv_style_set_shadow_color(&(theme_style.mod_btn), lv_color_make(9, 12, 8));
lv_style_set_shadow_width(&(theme_style.mod_btn), 3);
lv_style_set_shadow_spread(&(theme_style.mod_btn), 0);
lv_style_set_shadow_ofs_y(&(theme_style.mod_btn), 3);
lv_style_set_shadow_ofs_x(&(theme_style.mod_btn), 0);
lv_style_set_shadow_opa(&(theme_style.mod_btn), LV_OPA_COVER);
lv_obj_report_style_change(&(theme_style.mod_btn));

// ── mod_btn_pressed · active ──────────────────────────
lv_style_init(&(theme_style.mod_btn_pressed));
lv_style_set_text_font(&(theme_style.mod_btn_pressed), &montserratbold14);
lv_style_set_radius(&(theme_style.mod_btn_pressed), 10);
lv_style_set_bg_opa(&(theme_style.mod_btn_pressed), LV_OPA_COVER);
lv_style_set_bg_color(&(theme_style.mod_btn_pressed), lv_color_make(38, 49, 22));
lv_style_set_bg_grad_color(&(theme_style.mod_btn_pressed), lv_color_make(27, 34, 17));
lv_style_set_bg_grad_dir(&(theme_style.mod_btn_pressed), LV_GRAD_DIR_VER);
lv_style_set_border_color(&(theme_style.mod_btn_pressed), lv_color_make(96, 127, 52));
lv_style_set_border_width(&(theme_style.mod_btn_pressed), 3);
lv_style_set_border_side(&(theme_style.mod_btn_pressed), LV_BORDER_SIDE_BOTTOM);
lv_style_set_text_color(&(theme_style.mod_btn_pressed), lv_color_make(217, 242, 182));
lv_style_set_text_opa(&(theme_style.mod_btn_pressed), LV_OPA_COVER);
lv_style_set_pad_top(&(theme_style.mod_btn_pressed), 11);
lv_style_set_pad_bottom(&(theme_style.mod_btn_pressed), 11);
lv_style_set_pad_left(&(theme_style.mod_btn_pressed), 0);
lv_style_set_pad_right(&(theme_style.mod_btn_pressed), 0);
lv_style_set_translate_y(&(theme_style.mod_btn_pressed), 2);
lv_style_set_shadow_color(&(theme_style.mod_btn_pressed), lv_color_make(162, 208, 98));
lv_style_set_shadow_width(&(theme_style.mod_btn_pressed), 26);
lv_style_set_shadow_spread(&(theme_style.mod_btn_pressed), 5);
lv_style_set_shadow_ofs_y(&(theme_style.mod_btn_pressed), 0);
lv_style_set_shadow_ofs_x(&(theme_style.mod_btn_pressed), 0);
lv_style_set_shadow_opa(&(theme_style.mod_btn_pressed), 41);
lv_obj_report_style_change(&(theme_style.mod_btn_pressed));

// ── bar (slider fill) ─────────────────────────────────
lv_style_init(&(theme_style.bar));
lv_style_set_radius(&(theme_style.bar), 4);
lv_style_set_bg_color(&(theme_style.bar), lv_color_make(106, 151, 42));
lv_style_set_bg_grad_color(&(theme_style.bar), lv_color_make(83, 117, 36));
lv_style_set_bg_grad_dir(&(theme_style.bar), LV_GRAD_DIR_VER);
lv_style_set_bg_opa(&(theme_style.bar), LV_OPA_COVER);
lv_style_set_border_color(&(theme_style.bar), lv_color_make(192, 188, 181));
lv_style_set_border_width(&(theme_style.bar), 0);
lv_style_set_height(&(theme_style.bar), 9);
lv_style_set_shadow_color(&(theme_style.bar), lv_color_make(162, 208, 98));
lv_style_set_shadow_width(&(theme_style.bar), 10);
lv_style_set_shadow_opa(&(theme_style.bar), 66);
lv_obj_report_style_change(&(theme_style.bar));

// ── bar_background (groove) ───────────────────────────
lv_style_init(&(theme_style.bar_background));
lv_style_set_radius(&(theme_style.bar_background), 4);
lv_style_set_bg_color(&(theme_style.bar_background), lv_color_make(17, 19, 17));
lv_style_set_bg_grad_color(&(theme_style.bar_background), lv_color_make(17, 19, 17));
lv_style_set_bg_grad_dir(&(theme_style.bar_background), LV_GRAD_DIR_VER);
lv_style_set_bg_opa(&(theme_style.bar_background), LV_OPA_COVER);
lv_style_set_border_color(&(theme_style.bar_background), lv_color_make(15, 16, 15));
lv_style_set_border_width(&(theme_style.bar_background), 1);
lv_style_set_shadow_color(&(theme_style.bar_background), lv_color_make(192, 188, 181));
lv_style_set_shadow_width(&(theme_style.bar_background), 0);
lv_style_set_shadow_opa(&(theme_style.bar_background), LV_OPA_TRANSP);
lv_style_set_height(&(theme_style.bar_background), 9);
lv_obj_report_style_change(&(theme_style.bar_background));

// ── layer_name (header panel) ─────────────────────────
lv_style_init(&(theme_style.layer_name));
lv_style_set_text_font(&(theme_style.layer_name), &montserratbold14);
lv_style_set_radius(&(theme_style.layer_name), 8);
lv_style_set_bg_color(&(theme_style.layer_name), lv_color_make(27, 30, 26));
lv_style_set_bg_grad_color(&(theme_style.layer_name), lv_color_make(25, 27, 24));
lv_style_set_bg_grad_dir(&(theme_style.layer_name), LV_GRAD_DIR_VER);
lv_style_set_border_color(&(theme_style.layer_name), lv_color_make(15, 16, 14));
lv_style_set_text_color(&(theme_style.layer_name), lv_color_make(255, 255, 255));
lv_style_set_border_width(&(theme_style.layer_name), 1);
lv_obj_report_style_change(&(theme_style.layer_name));

// ── secondary_labels ──────────────────────────────────
lv_style_init(&(theme_style.secondary_labels));
lv_style_set_text_font(&(theme_style.secondary_labels), &montserratbold13);
lv_style_set_text_color(&(theme_style.secondary_labels), lv_color_make(168, 181, 150));
lv_obj_report_style_change(&(theme_style.secondary_labels));

// ── value_labels ──────────────────────────────────────
lv_style_init(&(theme_style.value_labels));
lv_style_set_text_color(&(theme_style.value_labels), lv_color_make(230, 232, 227));
lv_obj_report_style_change(&(theme_style.value_labels));

// ── flex_container (panel background) ────────────────
lv_style_init(&(theme_style.flex_container));
lv_style_set_bg_color(&(theme_style.flex_container), lv_color_make(22, 25, 21));
lv_style_set_bg_opa(&(theme_style.flex_container), LV_OPA_COVER);
lv_style_set_border_width(&(theme_style.flex_container), 0);
lv_obj_report_style_change(&(theme_style.flex_container));

}

void read_dilemma_theme_config_from_eeprom(dilemma_status_theme_t *config) {
    config->raw = eeconfig_read_user() & 0xff;
}

void write_dilemma_theme_config_to_eeprom(dilemma_status_theme_t *config) {
    eeconfig_update_user(config->raw);
}

void load_dilemma_theme_config_from_eeprom(void) {
    read_dilemma_theme_config_from_eeprom(&dilemma_lcd_theme);
}

void init_styles(void) {
    ui_styles = theme_style;
    update_styles_from_current_theme();
}

void update_styles_from_current_theme(void) {
    // TEST
    // static bool initialized = false;
    // if (!initialized) {
    //     ui_styles   = white_green;
    //     initialized = true;
    // } else {
    //     ui_styles = oxide_style;
    //     initialized = false;
    // }
    lv_obj_report_style_change(&ui_styles.mod_btn);
    lv_obj_report_style_change(&ui_styles.mod_btn_pressed);
    lv_obj_report_style_change(&ui_styles.layer_name);
    lv_obj_report_style_change(&ui_styles.secondary_labels);
    lv_obj_report_style_change(&ui_styles.bar);
    lv_obj_report_style_change(&ui_styles.bar_background);
    lv_obj_report_style_change(&ui_styles.flex_container);
}

uint8_t get_current_theme_id(void) {
    return dilemma_lcd_theme.current_theme_id;
}

void set_current_theme_id(uint8_t id) {
    dilemma_lcd_theme.current_theme_id = id;
}

void cycle_theme_and_save_in_eeprom(void) {
    // TODO
    // uint8_t new_id = (dilemma_lcd_theme.current_theme_id + 1) % (sizeof(themes) / sizeof(ui_theme *));
    // set_current_theme_id(new_id);
    // write_dilemma_theme_config_to_eeprom(&dilemma_lcd_theme);
}